import type { HTMLToMarkdownOptions } from 'mdream'
import type { WriteStream } from 'node:fs'
import type { BulkChunk, LlmsTxtConfig, ModuleOptions } from './runtime/types'
import type { LlmsTxtGeneratePayload } from '~/src/types'
import { createHash } from 'node:crypto'
import { createWriteStream, mkdirSync } from 'node:fs'
import { addPlugin, addServerHandler, addTypeTemplate, createResolver, defineNuxtModule, hasNuxtModule } from '@nuxt/kit'
import defu from 'defu'
import { TagIdMap } from 'mdream'
import { extractionPlugin } from 'mdream/plugins'
import { htmlToMarkdownSplitChunksStream } from 'mdream/splitter'
import { installNuxtSiteConfig, useSiteConfig, withSiteUrl } from 'nuxt-site-config/kit'
import { dirname, resolve as pathResolve, relative } from 'pathe'
import { readPackageJSON } from 'pkg-types'
import { estimateTokenCount } from 'tokenx'
import { logger } from './logger'
import { setupPrerenderHandler } from './prerender'

function generateVectorId(route: string, chunkIdx: number): string {
  const hash = createHash('sha256').update(route).digest('hex').substring(0, 48)
  return `${hash}-${chunkIdx}`
}

export interface ModuleHooks {
  /**
   * Hook to modify llms.txt content before final output
   * Other modules can append their own API endpoints here
   */
  'ai-ready:llms-txt': (payload: LlmsTxtGeneratePayload) => void | Promise<void>

  /**
   * Hook to add routes to the AI ready
   * Other modules can register their own API routes
   */
  'ai-ready:routes': (payload: { routes: Record<string, string> }) => void | Promise<void>
  /**
   * Hook called for each chunk generated during prerendering for bulk export
   */
  'ai-ready:chunk': (context: {
    chunk: BulkChunk
    route: string
    title: string
    description: string
    headings: Array<Record<string, string>>
  }) => void | Promise<void>
}

export interface ModulePublicRuntimeConfig {
  bulkRoute: string | false
  debug: boolean
  version: string
  mdreamOptions: ModuleOptions['mdreamOptions']
  markdownCacheHeaders: Required<NonNullable<ModuleOptions['markdownCacheHeaders']>>
}

export default defineNuxtModule<ModuleOptions>({
  meta: {
    name: 'nuxt-ai-ready',
    compatibility: {
      nuxt: '>=4.0.0',
    },
    configKey: 'aiReady',
  },
  moduleDependencies: {
    '@nuxtjs/robots': {
      version: '>=5.6.0',
    },
    'nuxt-site-config': {
      version: '>=3',
    },
    '@nuxtjs/mcp-toolkit': {
      version: '>=0.4.0',
      optional: true,
    },
  },
  defaults() {
    return {
      enabled: true,
      debug: false,
      bulkRoute: '/content.jsonl',
      mdreamOptions: {
        preset: 'minimal',
      } satisfies ModuleOptions['mdreamOptions'],
      markdownCacheHeaders: {
        maxAge: 3600, // 1 hour
        swr: true,
      },
    }
  },
  async setup(config, nuxt) {
    const { resolve } = createResolver(import.meta.url)
    const { version } = await readPackageJSON(resolve('../package.json'))

    logger.level = (config.debug || nuxt.options.debug) ? 4 : 3

    if (config.enabled === false) {
      logger.debug('Module is disabled, skipping setup.')
      return
    }

    // Install site config for accessing site name and description
    await installNuxtSiteConfig()

    // Set up alias
    nuxt.options.nitro.alias = nuxt.options.nitro.alias || {}
    nuxt.options.alias['#ai-ready'] = resolve('./runtime')

    // set default MCP name
    if (!nuxt.options.mcp?.name) {
      nuxt.options.mcp = nuxt.options.mcp || {}
      nuxt.options.mcp.name = useSiteConfig().name
    }

    // Add runtime server directories to Nitro scan
    nuxt.options.nitro.scanDirs = nuxt.options.nitro.scanDirs || []
    nuxt.options.nitro.scanDirs.push(
      resolve('./runtime/server/utils'),
      resolve('./runtime/server/mcp'),
    )

    if (typeof config.contentSignal === 'object') {
      nuxt.options.robots.groups.push({
        userAgent: '*',
        contentUsage: [`train-ai=${config.contentSignal.aiTrain ? 'y' : 'n'}`],
        contentSignal: [`ai-train=${config.contentSignal.aiTrain ? 'yes' : 'no'}`, `search=${config.contentSignal.search ? 'yes' : 'no'}`, `ai-input=${config.contentSignal.aiInput ? 'yes' : 'no'}`],
      })
    }

    addTypeTemplate({
      filename: 'module/nuxt-ai-ready.d.ts',
      getContents: (data) => {
        const typesPath = relative(resolve(data.nuxt!.options.rootDir, data.nuxt!.options.buildDir, 'module'), resolve('runtime/types'))
        const nitroTypes = `  interface NitroRuntimeHooks {
    'ai-ready:markdown': (context: import('${typesPath}').MarkdownContext) => void | Promise<void>
    'ai-ready:mdreamConfig': (config: import('mdream').HTMLToMarkdownOptions) => void | Promise<void>
  }`
        return `// Generated by nuxt-ai-ready
declare module 'nitropack/types' {
${nitroTypes}
}

declare module 'nitropack' {
${nitroTypes}
}

export {}
`
      },
    }, {
      nitro: true,
    })

    // Build default llms.txt config with API endpoints
    const defaultLlmsTxtSections: LlmsTxtConfig['sections'] = []

    if (config.bulkRoute !== false) {
      const resolvedBulkRoute = withSiteUrl(config.bulkRoute)
      defaultLlmsTxtSections.push({
        title: 'LLM Tools',
        links: [
          {
            title: 'Bulk Data',
            href: resolvedBulkRoute,
            description: `\`\`\`bash\ncurl "${resolvedBulkRoute}"\n\`\`\`\n\nReturns JSONL (newline-delimited JSON) with all indexed content.`,
          },
        ],
      })
    }

    const hasMCP = hasNuxtModule('@nuxtjs/mcp-toolkit')
    if (hasMCP) {
      // Register MCP definitions from runtime directory
      nuxt.hook('mcp:definitions:paths', (paths) => {
        const mcpRuntimeDir = resolve('./runtime/server/mcp')
        paths.tools = paths.tools || []
        paths.resources = paths.resources || []
        paths.prompts = paths.prompts || []
        paths.tools.push(`${mcpRuntimeDir}/tools`)
        paths.resources.push(`${mcpRuntimeDir}/resources`)
        paths.prompts.push(`${mcpRuntimeDir}/prompts`)
      })

      // Add MCP to the API endpoints section if bulk is enabled, or create new section
      const mcpLink = {
        title: 'MCP',
        href: withSiteUrl(nuxt.options.mcp?.route || '/mcp'),
      }

      if (config.bulkRoute !== false && defaultLlmsTxtSections[0]) {
        defaultLlmsTxtSections[0].links!.push(mcpLink)
      }
      else {
        defaultLlmsTxtSections.push({
          title: 'LLM Tools',
          links: [mcpLink],
        })
      }
    }

    // Merge default sections with user config
    const mergedLlmsTxt: LlmsTxtConfig = config.llmsTxt
      ? {
          sections: [
            ...defaultLlmsTxtSections,
            ...(config.llmsTxt.sections || []),
          ],
          notes: config.llmsTxt.notes,
        }
      : { sections: defaultLlmsTxtSections }

    nuxt.options.runtimeConfig['nuxt-ai-ready'] = {
      version: version || '0.0.0',
      debug: config.debug || false,
      bulkRoute: config.bulkRoute,
      mdreamOptions: config.mdreamOptions || {},
      markdownCacheHeaders: defu(config.markdownCacheHeaders, {
        maxAge: 3600,
        swr: true,
      }) as Required<NonNullable<ModuleOptions['markdownCacheHeaders']>>,
      llmsTxt: mergedLlmsTxt,
    } as any

    addServerHandler({
      middleware: true,
      handler: resolve('./runtime/server/middleware/mdream'),
    })

    if (nuxt.options.build) {
      addPlugin({ mode: 'server', src: resolve('./runtime/nuxt/plugins/prerender') })
    }
    if (nuxt.options.dev) {
      addServerHandler({ route: '/llms.txt', handler: resolve('./runtime/server/routes/llms.txt.get') })
    }

    // Setup prerendering hooks for static generation
    // @ts-expect-error untyped
    const isStatic = nuxt.options.nitro.static || nuxt.options._generate || false
    if (isStatic || nuxt.options.nitro.prerender?.routes?.length) {
      setupPrerenderHandler()
    }

    // Add route rules for static bulk file
    if (config.bulkRoute !== false) {
      nuxt.options.nitro.routeRules = nuxt.options.nitro.routeRules || {}
      nuxt.options.nitro.routeRules[config.bulkRoute] = {
        headers: {
          'Content-Type': 'application/x-ndjson; charset=utf-8',
        },
      }
    }

    // Bulk route served as static file (no handler needed)
    // MCP route handled by @nuxtjs/mcp-toolkit
    const isBuildMode = !nuxt.options._prepare && !nuxt.options.dev

    nuxt.hooks.hook('modules:done', () => {
      nuxt.hook('nitro:init', async (nitro) => {
        // Skip build-time indexing in dev mode
        if (!isBuildMode) {
          logger.debug('Dev mode: skipping llms.txt generation')
          return
        }

        // Skip bulk generation if disabled
        if (config.bulkRoute === false) {
          logger.debug('Bulk route disabled, skipping bulk generation')
          return
        }

        const bulkPath = pathResolve(nitro.options.output.dir, `public${config.bulkRoute}`)
        let bulkStream: WriteStream | null = null
        let bulkStreamEntries = 0
        nitro.hooks.hook('prerender:route', async (route) => {
          const isHtml = route.fileName?.endsWith('.html') && route.contents!.startsWith('<!DOCTYPE html')
          if (!isHtml || !route.contents) {
            return
          }
          // explicitely not in sitemap
          if (typeof route._sitemap !== 'undefined' && !route._sitemap) {
            return
          }
          let title = ''
          let description = ''
          const headings: Array<Record<string, string>> = []

          // Create extraction plugin first - must run before isolateMainPlugin
          const extractPlugin = extractionPlugin({
            title(el) {
              title = el.textContent
            },
            'meta[name="description"]': (el) => {
              description = el.attributes.content || ''
            },
            'h1, h2, h3, h4, h5, h6': (el) => {
              const text = el.textContent?.trim()
              const level = el.name.toLowerCase()
              if (text)
                headings.push({ [level]: text })
            },
          })

          const options: HTMLToMarkdownOptions = {
            origin: useSiteConfig().url,
            ...(config.mdreamOptions || {}),
          }

          // Apply preset if specified
          // options = withMinimalPreset(options)
          // Manually insert extraction plugin at the beginning, before all preset plugins
          options.plugins = [extractPlugin, ...(options.plugins || [])]

          const chunksStream = htmlToMarkdownSplitChunksStream(route.contents, {
            ...options,
            headersToSplitOn: [TagIdMap.h1, TagIdMap.h2, TagIdMap.h3],
            origin: useSiteConfig().url,
            chunkSize: 256,
            stripHeaders: false,
            lengthFunction(text) {
              return estimateTokenCount(text)
            },
          })

          // Create stream on first write
          if (!bulkStream) {
            mkdirSync(dirname(bulkPath), { recursive: true })
            bulkStream = createWriteStream(bulkPath)
            logger.info(`Bulk JSONL stream created at ${relative(nuxt.options.rootDir, bulkPath)}`)
          }

          logger.debug(`Processing chunks for route: ${route.route}`)

          // Stream chunks immediately without holding all in memory
          let idx = 0
          for await (const chunk of chunksStream) {
            logger.debug(`  Chunk ${idx}: ${chunk.content.length} chars, headers: ${JSON.stringify(chunk.metadata?.headers)}`)

            const bulkChunk: BulkChunk = {
              id: generateVectorId(route.route, idx),
              route: route.route,
              chunkIndex: idx,
              content: chunk.content,
              headers: chunk.metadata?.headers,
              loc: chunk.metadata?.loc,
              title,
              description,
            }

            // Call hook for modules to process chunk (e.g., RAG tooling)
            await nuxt.hooks.callHook('ai-ready:chunk', {
              chunk: bulkChunk,
              route: route.route,
              title,
              description,
              headings,
            })

            bulkStream.write(`${JSON.stringify(bulkChunk)}\n`)
            bulkStreamEntries++
            idx++
          }

          logger.debug(`Completed ${idx} chunks for ${route.route}`)
        })
        // Setup bulk JSONL stream path for low-memory bulk export
        nitro.hooks.hook('prerender:done', () => {
          // Close bulk JSONL stream if it was created
          if (bulkStream) {
            bulkStream.end()
            logger.success(`Bulk JSONL exported ${bulkStreamEntries} entries.`)
          }
        })
      })
    })
  },
})

export type { BulkChunk, ModuleOptions }
