import type { ParsedMarkdownResult } from './prerender'
import type { LlmsTxtConfig, ModuleOptions } from './runtime/types'
import { access, appendFile } from 'node:fs/promises'
import { join } from 'node:path'
import { addPlugin, addServerHandler, addTypeTemplate, createResolver, defineNuxtModule, hasNuxtModule } from '@nuxt/kit'
import defu from 'defu'
import { installNuxtSiteConfig, useSiteConfig, withSiteUrl } from 'nuxt-site-config/kit'
import { readPackageJSON } from 'pkg-types'
import { hookNuxtSeoProLicense } from './kit'
import { logger } from './logger'
import { setupPrerenderHandler } from './prerender'
import { refineDatabaseConfig, resolveDatabaseAdapter } from './utils/database'

export interface ModuleHooks {
  /**
   * Hook called when page markdown is generated during prerendering.
   * Called with route and markdown content when content has changed.
   */
  'ai-ready:page:markdown': (context: ParsedMarkdownResult & { route: string }) => void | Promise<void>
  /**
   * Hook to modify llms.txt configuration before it is finalized
   */
  'ai-ready:llms-txt': (payload: {
    sections: LlmsTxtConfig['sections']
    notes: string[]
  }) => void | Promise<void>
}

export interface ModulePublicRuntimeConfig {
  debug: boolean
  version: string
  mdreamOptions: ModuleOptions['mdreamOptions']
  markdownCacheHeaders: Required<NonNullable<ModuleOptions['markdownCacheHeaders']>>
  ttl: number
  database: {
    type: 'sqlite' | 'd1' | 'libsql'
    filename?: string
    bindingName?: string
    url?: string
    authToken?: string
  }
}

export default defineNuxtModule<ModuleOptions>({
  meta: {
    name: 'nuxt-ai-ready',
    compatibility: {
      nuxt: '>=4.0.0',
    },
    configKey: 'aiReady',
  },
  moduleDependencies: {
    '@nuxtjs/robots': {
      version: '>=5.6.0',
    },
    '@nuxtjs/sitemap': {
      version: '>=7',
    },
    'nuxt-site-config': {
      version: '>=3',
    },
    '@nuxtjs/mcp-toolkit': {
      version: '>=0.4.0',
      optional: true,
    },
  },
  defaults() {
    return {
      enabled: true,
      debug: false,
      mdreamOptions: {
        preset: 'minimal',
      } satisfies ModuleOptions['mdreamOptions'],
      markdownCacheHeaders: {
        maxAge: 3600, // 1 hour
        swr: true,
      },
      cacheMaxAgeSeconds: 600, // 10 minutes
    }
  },
  async setup(config, nuxt) {
    const { resolve } = createResolver(import.meta.url)
    const { version } = await readPackageJSON(resolve('../package.json'))

    logger.level = (config.debug || nuxt.options.debug) ? 4 : 3

    if (config.enabled === false) {
      logger.debug('Module is disabled, skipping setup.')
      return
    }

    // Install site config for accessing site name and description
    await installNuxtSiteConfig()
    hookNuxtSeoProLicense()

    // Set up alias
    nuxt.options.nitro.alias = nuxt.options.nitro.alias || {}
    nuxt.options.alias['#ai-ready'] = resolve('./runtime')

    // Resolve database adapter alias at build time
    const resolverOpts = { resolver: createResolver(import.meta.url) }
    const dbType = config.database?.type || 'sqlite'
    const adapterPath = await resolveDatabaseAdapter(dbType, resolverOpts)
    nuxt.options.alias['#ai-ready/adapter'] = adapterPath
    nuxt.options.nitro.alias['#ai-ready/adapter'] = adapterPath

    // set default MCP name
    if (!nuxt.options.mcp?.name) {
      nuxt.options.mcp = nuxt.options.mcp || {}
      nuxt.options.mcp.name = useSiteConfig().name
    }

    // Add runtime server directories to Nitro scan
    nuxt.options.nitro.scanDirs = nuxt.options.nitro.scanDirs || []
    nuxt.options.nitro.scanDirs.push(
      resolve('./runtime/server/utils'),
    )

    if (typeof config.contentSignal === 'object') {
      nuxt.options.robots = nuxt.options.robots || {}
      nuxt.options.robots.groups = nuxt.options.robots.groups || []
      nuxt.options.robots.groups.push({
        userAgent: '*',
        contentUsage: [`train-ai=${config.contentSignal.aiTrain ? 'y' : 'n'}`],
        contentSignal: [`ai-train=${config.contentSignal.aiTrain ? 'yes' : 'no'}`, `search=${config.contentSignal.search ? 'yes' : 'no'}`, `ai-input=${config.contentSignal.aiInput ? 'yes' : 'no'}`],
      })
    }

    // Publish Nitro hook types for consuming apps
    addTypeTemplate({
      filename: 'types/nuxt-ai-ready.d.ts',
      getContents: () => `// Generated by nuxt-ai-ready
import type { MarkdownContext, PageIndexedContext } from 'nuxt-ai-ready'
import type { HTMLToMarkdownOptions } from 'mdream'

declare module 'nitropack/types' {
  interface NitroRuntimeHooks {
    'ai-ready:markdown': (context: MarkdownContext) => void | Promise<void>
    'ai-ready:mdreamConfig': (config: HTMLToMarkdownOptions) => void | Promise<void>
    'ai-ready:page:indexed': (context: PageIndexedContext) => void | Promise<void>
  }
}

declare module '#ai-ready-virtual/read-page-data.mjs' {
  export function readPageDataFromFilesystem(): Promise<{
    pages: Array<{
      route: string
      title: string
      description: string
      headings: string
      keywords: string[]
      updatedAt: string
      markdown: string
    }>
    errorRoutes: string[]
  }>
}

declare module '#ai-ready-virtual/page-data.mjs' {
  export const pages: never[]
}

declare module '#ai-ready/adapter' {
  import type { Connector } from 'db0'
  const connector: (config: unknown) => Connector
  export default connector
}

export {}
`,
    }, { nitro: true })

    // Build default llms.txt config with API endpoints
    const defaultLlmsTxtSections: LlmsTxtConfig['sections'] = []
    const llmsFullRoute = withSiteUrl('llms-full.txt')
    defaultLlmsTxtSections.push({
      title: 'LLM Resources',
      links: [
        {
          title: 'Full Content',
          href: llmsFullRoute,
          description: 'Complete page content in markdown format.',
        },
      ],
    })

    const hasMCP = hasNuxtModule('@nuxtjs/mcp-toolkit')
    if (hasMCP) {
      // Register MCP definitions from runtime directory
      nuxt.hook('mcp:definitions:paths', (paths) => {
        const mcpRuntimeDir = resolve(`./runtime/server/mcp`)
        const mcpConfig = config.mcp || {}
        if (mcpConfig.tools !== false)
          (paths.tools ||= []).push(`${mcpRuntimeDir}/tools`)
        if (mcpConfig.resources !== false)
          (paths.resources ||= []).push(`${mcpRuntimeDir}/resources`)
      })

      // Add MCP to the API endpoints section if bulk is enabled, or create new section
      const mcpLink = {
        title: 'MCP',
        href: withSiteUrl(nuxt.options.mcp?.route || '/mcp'),
        description: 'Model Context Protocol server endpoint for AI agent integration.',
      }

      if (defaultLlmsTxtSections[0]) {
        defaultLlmsTxtSections[0].links!.push(mcpLink)
      }
      else {
        defaultLlmsTxtSections.push({
          title: 'LLM Tools',
          links: [mcpLink],
        })
      }
    }

    // Merge default sections with user config
    const mergedLlmsTxt: LlmsTxtConfig = config.llmsTxt
      ? {
          sections: [
            ...defaultLlmsTxtSections,
            ...(config.llmsTxt.sections || []),
          ],
          notes: config.llmsTxt.notes,
        }
      : { sections: defaultLlmsTxtSections }

    // Allow other modules to extend llms.txt content via hook
    const llmsTxtPayload = {
      sections: mergedLlmsTxt.sections || [],
      notes: typeof mergedLlmsTxt.notes === 'string' ? [mergedLlmsTxt.notes] : (mergedLlmsTxt.notes || []),
    }
    await nuxt.callHook('ai-ready:llms-txt', llmsTxtPayload)
    mergedLlmsTxt.sections = llmsTxtPayload.sections
    mergedLlmsTxt.notes = llmsTxtPayload.notes.length > 0 ? llmsTxtPayload.notes : undefined

    const prerenderCacheDir = join(nuxt.options.rootDir, 'node_modules/.cache/nuxt-seo/ai-ready/routes')
    const pageDataPath = join(nuxt.options.buildDir, '.data/ai-ready/page-data.jsonl')

    // Virtual module for page data - different behavior for prerender vs runtime
    nuxt.hooks.hook('nitro:config', (nitroConfig) => {
      // Enable async context to allow useEvent() in nested functions (MCP handlers, etc.)
      // This enables access to H3Event and Cloudflare bindings from any async context
      nitroConfig.experimental = nitroConfig.experimental || {}
      nitroConfig.experimental.asyncContext = true

      nitroConfig.virtual = nitroConfig.virtual || {}

      // Helper to read JSONL from filesystem during prerender
      // Entries with _error: true are error routes, others are page data
      nitroConfig.virtual['#ai-ready-virtual/read-page-data.mjs'] = `
import { readFile } from 'node:fs/promises'

export async function readPageDataFromFilesystem() {
  if (!import.meta.prerender) {
    return { pages: [], errorRoutes: [] }
  }
  const data = await readFile(${JSON.stringify(pageDataPath)}, 'utf-8').catch(() => null)
  if (!data) return { pages: [], errorRoutes: [] }
  const entries = data.trim().split('\\n').filter(Boolean).map(line => JSON.parse(line))
  const pages = entries.filter(e => !e._error)
  const errorRoutes = entries.filter(e => e._error).map(e => e.route)
  return { pages, errorRoutes }
}
`
      // Runtime module exports empty arrays (prerendered data read from filesystem)
      nitroConfig.virtual['#ai-ready-virtual/page-data.mjs'] = `export const pages = []\nexport const errorRoutes = []`
    })

    // Resolve database config
    const database = refineDatabaseConfig(config.database || {}, nuxt.options.rootDir)

    nuxt.options.runtimeConfig['nuxt-ai-ready'] = {
      version: version || '0.0.0',
      debug: config.debug || false,
      mdreamOptions: config.mdreamOptions || {},
      markdownCacheHeaders: defu(config.markdownCacheHeaders, {
        maxAge: 3600,
        swr: true,
      }) as Required<NonNullable<ModuleOptions['markdownCacheHeaders']>>,
      llmsTxt: mergedLlmsTxt,
      cacheMaxAgeSeconds: config.cacheMaxAgeSeconds ?? 600,
      prerenderCacheDir,
      ttl: config.ttl ?? 0,
      database,
    } as any

    // Register plugins
    nuxt.options.nitro.plugins = nuxt.options.nitro.plugins || []
    // db-restore: loads compressed dump on cold start for serverless
    nuxt.options.nitro.plugins.push(resolve('./runtime/server/plugins/db-restore'))
    // page-indexer: indexes pages on visit via afterResponse hook
    nuxt.options.nitro.plugins.push(resolve('./runtime/server/plugins/page-indexer'))

    addServerHandler({
      middleware: true,
      handler: resolve('./runtime/server/middleware/markdown.prerender'),
    })
    addServerHandler({
      middleware: true,
      handler: resolve('./runtime/server/middleware/markdown'),
    })

    if (nuxt.options.build) {
      addPlugin({
        mode: 'server',
        src: resolve('./runtime/nuxt/plugins/md-hints.prerender'),
      })
    }
    // gets replaced with a static file
    addServerHandler({ route: '/llms.txt', handler: resolve('./runtime/server/routes/llms.txt.get') })
    addServerHandler({ route: '/llms-full.txt', handler: resolve('./runtime/server/routes/llms-full.txt.get') })

    // Debug endpoint (only accessible when debug: true)
    if (config.debug) {
      addServerHandler({ route: '/__ai-ready-debug', handler: resolve('./runtime/server/routes/__ai-ready-debug.get') })
    }

    // Setup prerendering hooks for static generation
    // @ts-expect-error untyped
    const isStatic = nuxt.options.nitro.static || nuxt.options._generate || false
    const hasPrerenderedRoutes = nuxt.options.nitro.prerender?.routes?.length
    const isSPA = nuxt.options.ssr === false

    if (!nuxt.options.dev && !nuxt.options._prepare) {
      // Warn about unsupported/limited modes
      if (isSPA && !hasPrerenderedRoutes) {
        logger.warn('SPA mode detected without prerendering. llms-full.txt will not be generated.')
        logger.warn('For full functionality, enable SSR or prerender routes.')
      }
      else if (!isStatic && !hasPrerenderedRoutes) {
        logger.info('SSR-only mode: llms-full.txt requires prerendering. Runtime markdown conversion available.')
      }
    }

    if (isStatic || hasPrerenderedRoutes) {
      const siteConfig = useSiteConfig()
      setupPrerenderHandler(pageDataPath, {
        name: siteConfig.name,
        url: siteConfig.url,
        description: siteConfig.description,
      }, mergedLlmsTxt)
    }

    // Add route rules for static files with proper charset
    nuxt.options.nitro.routeRules = nuxt.options.nitro.routeRules || {}
    nuxt.options.nitro.routeRules['/llms.txt'] = { headers: { 'Content-Type': 'text/plain; charset=utf-8' } }
    nuxt.options.nitro.routeRules['/llms-full.txt'] = { headers: { 'Content-Type': 'text/plain; charset=utf-8' } }

    // Append charset header for .md files to _headers (Cloudflare Pages)
    // The splat (*) greedily matches all characters including slashes, so /*.md matches all depths
    nuxt.hooks.hook('nitro:build:before', (nitro) => {
      nitro.hooks.hook('compiled', async () => {
        const headersPath = join(nitro.options.output.publicDir, '_headers')
        const exists = await access(headersPath).then(() => true).catch(() => false)
        if (exists) {
          await appendFile(headersPath, `
/*.md
  Content-Type: text/markdown; charset=utf-8
`)
          logger.debug('Appended .md charset header to _headers')
        }
      })
    })
  },
})

export type { ModuleOptions } from './runtime/types'
