import type { ProcessedFile } from 'mdream/llms-txt'
import type { Nitro, PrerenderRoute } from 'nitropack'
import type { WriteStream } from 'node:fs'
import type { BulkChunk } from './runtime/types'
import { createHash } from 'node:crypto'
import { createWriteStream, mkdirSync } from 'node:fs'
import { stat } from 'node:fs/promises'
import { dirname, join, relative } from 'node:path'
import { useNuxt } from '@nuxt/kit'
import { createLlmsTxtStream } from 'mdream/llms-txt'
import { useSiteConfig } from 'nuxt-site-config/kit'
import { logger } from './logger'

function generateVectorId(route: string, chunkIdx: number): string {
  const hash = createHash('sha256').update(route).digest('hex').substring(0, 48)
  return `${hash}-${chunkIdx}`
}

export function setupPrerenderHandler() {
  const nuxt = useNuxt()

  nuxt.hooks.hook('nitro:init', async (nitro: Nitro) => {
    let writer: WritableStreamDefaultWriter<ProcessedFile> | null = null
    let bulkStream: WriteStream | null = null
    let bulkStreamEntries = 0
    let pageCount = 0
    const startTime = Date.now()
    const bulkPath = join(nitro.options.output.publicDir, 'content.jsonl')

    nitro.hooks.hook('prerender:generate', async (route) => {
      // Process markdown files generated by our middleware
      if (!route.fileName?.endsWith('.md')) {
        return
      }

      // Convert .md route to actual page route (e.g., /index.md -> /, /about.md -> /about)
      let pageRoute = route.route.replace(/\.md$/, '')
      if (pageRoute === '/index') {
        pageRoute = '/'
      }

      // Initialize streams on first page
      if (!writer) {
        const siteConfig = useSiteConfig()
        const stream = createLlmsTxtStream({
          siteName: siteConfig.name || siteConfig.url,
          description: siteConfig.description,
          origin: siteConfig.url,
          generateFull: true,
          outputDir: nitro.options.output.publicDir,
        })
        writer = stream.getWriter()
      }

      if (!bulkStream) {
        mkdirSync(dirname(bulkPath), { recursive: true })
        bulkStream = createWriteStream(bulkPath)
        logger.info(`Bulk JSONL stream created at ${relative(nuxt.options.rootDir, bulkPath)}`)
      }

      const { chunks, title, description, headings } = JSON.parse(route.contents || '{}') as {
        chunks: Array<{ content: string, metadata?: { headers?: Record<string, string>, loc?: { lines: { from: number, to: number } } } }>
        title: string
        description: string
        headings: Array<Record<string, string>>
      }

      // Reassemble full markdown from chunks for llms.txt
      const markdown = chunks.map(c => c.content).join('\n\n')

      // Stream page to llms.txt
      await writer.write({
        filePath: route.fileName,
        url: pageRoute,
        title,
        content: markdown,
        metadata: {
          description,
          title,
        },
      })
      pageCount++

      // Process chunks for bulk JSONL
      logger.debug(`Processing ${chunks.length} chunks for route: ${pageRoute}`)
      for (let idx = 0; idx < chunks.length; idx++) {
        const chunk = chunks[idx]
        if (!chunk)
          continue

        const bulkChunk: BulkChunk = {
          id: generateVectorId(pageRoute, idx),
          route: pageRoute,
          chunkIndex: idx,
          content: chunk.content,
          headers: chunk.metadata?.headers,
          loc: chunk.metadata?.loc,
          title,
          description,
        }

        // Call hook for modules to process chunk (e.g., RAG tooling)
        await nuxt.hooks.callHook('ai-ready:chunk', {
          chunk: bulkChunk,
          route: pageRoute,
          title,
          description,
          headings,
        })

        bulkStream.write(`${JSON.stringify(bulkChunk)}\n`)
        bulkStreamEntries++
      }
      logger.debug(`Completed ${chunks.length} chunks for ${pageRoute}`)

      // Set page content to the markdown
      route.contents = markdown
    })

    nitro.hooks.hook('prerender:done', async () => {
      if (!writer) {
        return
      }

      await writer.close()

      // Close bulk stream if created
      if (bulkStream) {
        bulkStream.end()
        logger.info(`Bulk JSONL stream closed with ${bulkStreamEntries} chunks`)
      }

      // Register generated files with prerender
      const llmsTxtPath = join(nitro.options.output.publicDir, 'llms.txt')
      const llmsFullTxtPath = join(nitro.options.output.publicDir, 'llms-full.txt')

      const files: PrerenderRoute[] = [
        {
          route: '/llms.txt',
          fileName: llmsTxtPath,
          generateTimeMS: 0,
        },
        {
          route: '/llms-full.txt',
          fileName: llmsFullTxtPath,
          generateTimeMS: 0,
        },
      ]

      if (bulkStream) {
        files.push({
          route: '/content.jsonl',
          fileName: bulkPath,
          generateTimeMS: 0,
        })
      }

      const [llmsStats, llmsFullStats, bulkStats] = await Promise.all([
        stat(llmsTxtPath),
        stat(llmsFullTxtPath),
        bulkStream ? stat(bulkPath) : Promise.resolve(null),
      ])

      nitro._prerenderedRoutes!.push(...files)

      const elapsed = Date.now() - startTime
      const llmsKb = (llmsStats.size / 1024).toFixed(2)
      const llmsFullKb = (llmsFullStats.size / 1024).toFixed(2)
      const bulkKb = bulkStats ? (bulkStats.size / 1024).toFixed(2) : '0'
      logger.info(`Generated llms.txt (${llmsKb}kb), llms-full.txt (${llmsFullKb}kb), and content.jsonl (${bulkKb}kb) from ${pageCount} pages (${bulkStreamEntries} chunks) in ${elapsed}ms`)
    })
  })
}
