import type { ProcessedFile } from 'mdream/llms-txt'
import type { Nitro, PrerenderRoute } from 'nitropack'
import { stat } from 'node:fs/promises'
import { join } from 'node:path'
import { useNuxt } from '@nuxt/kit'
import { createLlmsTxtStream } from 'mdream/llms-txt'
import { useSiteConfig } from 'nuxt-site-config/kit'
import { logger } from './logger'

export function setupPrerenderHandler() {
  const nuxt = useNuxt()

  nuxt.hooks.hook('nitro:init', async (nitro: Nitro) => {
    let writer: WritableStreamDefaultWriter<ProcessedFile> | null = null
    let pageCount = 0
    const startTime = Date.now()

    nitro.hooks.hook('prerender:generate', async (route) => {
      // Process markdown files generated by our middleware
      if (!route.fileName?.endsWith('.md')) {
        return
      }

      // Initialize stream on first page
      if (!writer) {
        const siteConfig = useSiteConfig()
        const stream = createLlmsTxtStream({
          siteName: siteConfig.name || siteConfig.url,
          description: siteConfig.description,
          origin: siteConfig.url,
          generateFull: true,
          outputDir: nitro.options.output.publicDir,
        })
        writer = stream.getWriter()
      }

      const { markdown, title, description } = JSON.parse(route.contents || '{}') as {
        markdown: string
        title: string
        description: string
      }

      // Stream page immediately
      await writer.write({
        filePath: route.fileName,
        url: route.route,
        title,
        content: markdown,
        metadata: {
          description,
          title,
        },
      })
      pageCount++

      // Set page content to the markdown
      route.contents = markdown
    })

    nitro.hooks.hook('prerender:done', async () => {
      if (!writer) {
        return
      }

      await writer.close()

      // Register generated files with prerender
      const llmsTxtPath = join(nitro.options.output.publicDir, 'llms.txt')
      const llmsFullTxtPath = join(nitro.options.output.publicDir, 'llms-full.txt')

      const [llmsStats, llmsFullStats] = await Promise.all([
        stat(llmsTxtPath),
        stat(llmsFullTxtPath),
      ])

      nitro._prerenderedRoutes!.push(
        {
          route: '/llms.txt',
          fileName: llmsTxtPath,
          generateTimeMS: 0,
        } satisfies PrerenderRoute,
        {
          route: '/llms-full.txt',
          fileName: llmsFullTxtPath,
          generateTimeMS: 0,
        } satisfies PrerenderRoute,
      )

      const elapsed = Date.now() - startTime
      const llmsKb = (llmsStats.size / 1024).toFixed(2)
      const llmsFullKb = (llmsFullStats.size / 1024).toFixed(2)
      logger.info(`Generated llms.txt (${llmsKb}kb) and llms-full.txt (${llmsFullKb}kb) from ${pageCount} pages in ${elapsed}ms`)
    })
  })
}
