import type { Nuxt } from '@nuxt/schema'
import type { NitroRuntimeCompatibility } from 'nuxtseo-shared/kit'
import type { ModuleOptions } from './runtime/types'
import { addTemplate, addTypeTemplate } from '@nuxt/kit'
import { renderNitroTypeAugmentations } from 'nuxtseo-shared/kit'

interface TemplateContext {
  nuxt: Nuxt
  config: ModuleOptions
  nitroCompatibility: NitroRuntimeCompatibility
}

/**
 * Types for the WebMCP declarative API, which turns an annotated form into a
 * tool. Only emitted when WebMCP is enabled so the attributes stay out of
 * autocomplete for everyone else.
 * @see https://developer.chrome.com/docs/ai/webmcp/declarative-api
 */
const declarativeWebMcpTypes = `
import type { WebMcpToolsContext } from 'nuxt-ai-ready/webmcp'

declare module '#app' {
  interface RuntimeNuxtHooks {
    /** Mutate built-in browser tools and their registration options before registration. */
    'ai-ready:webmcp:tools': (context: WebMcpToolsContext) => void | Promise<void>
  }
}

declare module '@vue/runtime-dom' {
  interface HTMLAttributes {
    /** Names the tool this form exposes to agents. */
    toolname?: string
    /** Describes what submitting this form does. */
    tooldescription?: string
    /** Describes this field as a tool parameter. */
    toolparamdescription?: string
    /** Submit the form as soon as an agent fills it in. */
    toolautosubmit?: boolean | ''
  }
}

declare global {
  interface SubmitEvent {
    /** Whether an agent triggered this submit through a tool call. */
    readonly agentInvoked?: boolean
    /** Return a result to the agent. Call preventDefault() first. */
    respondWith?: (result: Promise<unknown>) => void
  }

  interface WebMcpToolEvent extends Event {
    readonly toolName: string
  }

  interface WindowEventMap {
    toolactivated: WebMcpToolEvent
    toolcancel: WebMcpToolEvent
  }
}
`

export function registerTypeTemplates(ctx: TemplateContext) {
  const nitroTypes = renderNitroTypeAugmentations(ctx.nitroCompatibility, {
    runtimeHooks: `'ai-ready:page:markdown': (context: MarkdownContext) => void | Promise<void>
'ai-ready:mdreamConfig': (config: MdreamOptions) => void | Promise<void>
'ai-ready:page:indexed': (context: PageIndexedContext) => void | Promise<void>`,
  })

  // Type augmentations for existing modules
  addTypeTemplate({
    filename: 'types/nuxt-ai-ready-augments.d.ts',
    getContents: () => `// Generated by nuxt-ai-ready
/// <reference path="./ai-ready-virtual.d.ts" />
import type { MarkdownContext, PageIndexedContext } from 'nuxt-ai-ready'
import type { MdreamOptions } from 'mdream'

${nitroTypes}
${ctx.config.webmcp ? declarativeWebMcpTypes : ''}
export {}
`,
  })

  // Type definitions for virtual modules
  addTemplate({
    filename: 'types/ai-ready-virtual.d.ts',
    getContents: () => `declare module '#ai-ready-virtual/read-page-data.mjs' {
  export function readMarkdownLinkAvailabilityFromFilesystem(): Promise<{
    runtimeMarkdownAvailable: boolean
    paths: string[]
  }>
  export function readPageDataFromFilesystem(): Promise<{
    pages: Array<{
      route: string
      title: string
      description: string
      headings: string
      keywords: string[]
      updatedAt: string
      markdown: string
    }>
    errorRoutes: string[]
  }>
}

declare module '#ai-ready-virtual/page-data.mjs' {
  export const pages: never[]
}

declare module '#ai-ready-virtual/logger.mjs' {
  import type { ConsolaInstance } from 'consola'
  export const logger: ConsolaInstance
}

declare module '#ai-ready-virtual/db-provider.mjs' {
  import type { H3Event } from '#nuxtseo/h3'
  import type { DrizzleDatabase } from '#ai-ready/server/db/drizzle/client'
  export function createClient(event?: H3Event): Promise<DrizzleDatabase>
}

declare module '#ai-ready-virtual/db-schema.mjs' {
  export * from '#ai-ready/server/db/schema/sqlite'
}

declare module '#ai-ready-virtual/content-lookup.mjs' {
  import type { H3Event } from '#nuxtseo/h3'
  export function lookupContentPage(event: H3Event, path: string): Promise<{
    markdown: string
    title?: string
    description?: string
    updatedAt?: string
  } | null>
}

declare module '#ai-ready-virtual/agent-skills.mjs' {
  import type { AgentSkillsIndex } from 'nuxt-ai-ready'
  export const agentSkillsIndex: AgentSkillsIndex | null
  export const localAgentSkillArtifacts: Record<string, string>
}
`,
  })
}
