import type { Nuxt } from '@nuxt/schema'
import type { ModuleOptions } from './runtime/types'
import { addTemplate, addTypeTemplate } from '@nuxt/kit'

interface TemplateContext {
  nuxt: Nuxt
  config: ModuleOptions
}

export function registerTypeTemplates(_ctx: TemplateContext) {
  // Type augmentations for existing modules
  addTypeTemplate({
    filename: 'types/nuxt-ai-ready-augments.d.ts',
    getContents: () => `// Generated by nuxt-ai-ready
/// <reference path="./ai-ready-virtual.d.ts" />
import type { MarkdownContext, PageIndexedContext } from 'nuxt-ai-ready'
import type { MdreamOptions } from 'mdream'

declare module 'nitropack/types' {
  interface NitroRuntimeHooks {
    'ai-ready:markdown': (context: MarkdownContext) => void | Promise<void>
    'ai-ready:mdreamConfig': (config: MdreamOptions) => void | Promise<void>
    'ai-ready:page:indexed': (context: PageIndexedContext) => void | Promise<void>
  }
}

export {}
`,
  })

  // Type definitions for virtual modules
  addTemplate({
    filename: 'types/ai-ready-virtual.d.ts',
    getContents: () => `declare module '#ai-ready-virtual/read-page-data.mjs' {
  export function readPageDataFromFilesystem(): Promise<{
    pages: Array<{
      route: string
      title: string
      description: string
      headings: string
      keywords: string[]
      updatedAt: string
      markdown: string
    }>
    errorRoutes: string[]
  }>
}

declare module '#ai-ready-virtual/page-data.mjs' {
  export const pages: never[]
}

declare module '#ai-ready-virtual/logger.mjs' {
  import type { ConsolaInstance } from 'consola'
  export const logger: ConsolaInstance
}

declare module '#ai-ready-virtual/db-provider.mjs' {
  import type { H3Event } from 'h3'
  import type { DrizzleDatabase } from '#ai-ready/server/db/drizzle/client'
  export function createClient(event?: H3Event): Promise<DrizzleDatabase>
}

declare module '#ai-ready-virtual/db-schema.mjs' {
  export * from '#ai-ready/server/db/schema/sqlite'
}
`,
  })
}
