import type { Nuxt } from '@nuxt/schema'
import type { ModuleOptions } from './runtime/types'
import { addTypeTemplate } from '@nuxt/kit'

interface TemplateContext {
  nuxt: Nuxt
  config: ModuleOptions
}

export function registerTypeTemplates(_ctx: TemplateContext) {
  // Nitro runtime hooks and virtual module types
  addTypeTemplate({
    filename: 'types/nuxt-ai-ready.d.ts',
    getContents: () => `// Generated by nuxt-ai-ready
import type { MarkdownContext, PageIndexedContext } from 'nuxt-ai-ready'
import type { HTMLToMarkdownOptions } from 'mdream'

declare module 'nitropack/types' {
  interface NitroRuntimeHooks {
    'ai-ready:markdown': (context: MarkdownContext) => void | Promise<void>
    'ai-ready:mdreamConfig': (config: HTMLToMarkdownOptions) => void | Promise<void>
    'ai-ready:page:indexed': (context: PageIndexedContext) => void | Promise<void>
  }
}

declare module '#ai-ready-virtual/read-page-data.mjs' {
  export function readPageDataFromFilesystem(): Promise<{
    pages: Array<{
      route: string
      title: string
      description: string
      headings: string
      keywords: string[]
      updatedAt: string
      markdown: string
    }>
    errorRoutes: string[]
  }>
}

declare module '#ai-ready-virtual/page-data.mjs' {
  export const pages: never[]
}

declare module '#ai-ready/adapter' {
  import type { Connector } from 'db0'
  const connector: (config: unknown) => Connector
  export default connector
}

declare module '#ai-ready/db-provider' {
  import type { H3Event } from 'h3'
  import type { Connector } from 'db0'
  export function createConnector(event?: H3Event): Promise<Connector>
}

export {}
`,
  })
}
