import type { ModuleAppRuntimeConfig } from '../../../module'
import type { WebMcpRegisterOptions, WebMcpToolsContext } from '../../webmcp'
import { defineNuxtPlugin, useRuntimeConfig } from 'nuxt/app'
import { checkToolBudget, getModelContext, registerTool } from '../../webmcp'
import { createSiteTools } from '../../webmcp-site-tools'
import { setWebMcpDefaults } from '../webmcp-config'

export default defineNuxtPlugin({
  name: 'nuxt-ai-ready:webmcp',
  setup(nuxtApp) {
    const runtimeConfig = useRuntimeConfig()
    const { webmcp } = runtimeConfig.public['nuxt-ai-ready'] as ModuleAppRuntimeConfig
    setWebMcpDefaults(webmcp)

    nuxtApp.hook('app:created', async () => {
      const modelContext = getModelContext()
      if (!modelContext)
        return

      const registerOptions: WebMcpRegisterOptions = {}
      if (webmcp.exposedTo?.length)
        registerOptions.exposedTo = webmcp.exposedTo

      const toolRegisterOptions: Record<string, WebMcpRegisterOptions> = {}
      const setExposedTo = (name: string, exposedTo: string[] | undefined) => {
        if (exposedTo !== undefined)
          toolRegisterOptions[name] = { exposedTo }
      }
      setExposedTo('list_pages', webmcp.tools.listPages?.exposedTo)
      setExposedTo('search_pages', webmcp.tools.searchPages?.exposedTo)
      setExposedTo('get_page_markdown', webmcp.tools.getPageMarkdown?.exposedTo)

      const context: WebMcpToolsContext = {
        tools: createSiteTools({
          baseURL: runtimeConfig.app.baseURL,
          tools: {
            listPages: webmcp.tools.listPages
              ? {
                  defaultLimit: webmcp.tools.listPages.defaultLimit,
                  maxOutputChars: webmcp.tools.listPages.maxOutputChars,
                }
              : { enabled: false },
            searchPages: webmcp.tools.searchPages
              ? {
                  defaultLimit: webmcp.tools.searchPages.defaultLimit,
                  maxOutputChars: webmcp.tools.searchPages.maxOutputChars,
                }
              : { enabled: false },
            getPageMarkdown: webmcp.tools.getPageMarkdown
              ? { maxOutputChars: webmcp.tools.getPageMarkdown.maxOutputChars }
              : { enabled: false },
          },
        }),
        registerOptions,
        toolRegisterOptions,
      }
      // Consumer types are generated by the module when WebMCP is enabled.
      await nuxtApp.callHook('ai-ready:webmcp:tools' as any, context)

      for (const tool of context.tools) {
        if (import.meta.dev) {
          for (const warning of checkToolBudget(tool))
            console.warn(`[nuxt-ai-ready] ${warning}`)
        }
        const result = await registerTool(modelContext, tool, {
          ...context.registerOptions,
          ...context.toolRegisterOptions[tool.name],
        })
        if (result._tag === 'Error')
          console.error(`[nuxt-ai-ready] Failed to register WebMCP tool "${tool.name}".`, result.error)
      }
    })
  },
})
